package com.bhawani.product_api.service;


import com.bhawani.product_api.entity.Product;
import com.bhawani.product_api.exception.ProductNotFoundException;
import com.bhawani.product_api.repository.ProductRepository;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * Contains the business logic for product operations.
 */
@Service
public class ProductServiceImpl implements ProductService {

    private final ProductRepository productRepository;

    /**
     * Constructor injection is preferred over field injection.
     *
     * Benefits:
     * - Dependency is mandatory
     * - Class is easier to test
     * - Field can remain final
     * - Avoids hidden dependencies
     */
    public ProductServiceImpl(ProductRepository productRepository) {
        this.productRepository = productRepository;
    }

    @Override
    public Product createProduct(Product product) {

        /*
         * ID should always be generated by the database.
         * The client should not control it.
         */
        product.setId(null);

        return productRepository.save(product);
    }

    @Override
    public List<Product> getAllProducts() {
        return productRepository.findAll();
    }

    @Override
    public Product getProductById(Long productId) {

        return productRepository.findById(productId)
                .orElseThrow(
                        () -> new ProductNotFoundException(productId)
                );
    }

    @Override
    public Product updateProduct(
            Long productId,
            Product updatedProduct
    ) {

        Product existingProduct = getProductById(productId);

        /*
         * Update the existing managed entity rather than
         * creating a completely unrelated record.
         */
        existingProduct.setName(updatedProduct.getName());
        existingProduct.setSku(updatedProduct.getSku());
        existingProduct.setDescription(updatedProduct.getDescription());
        existingProduct.setPrice(updatedProduct.getPrice());
        existingProduct.setQuantity(updatedProduct.getQuantity());
        existingProduct.setCategory(updatedProduct.getCategory());
        existingProduct.setActive(updatedProduct.getActive());

        return productRepository.save(existingProduct);
    }

    @Override
    public void deleteProduct(Long productId) {

        Product existingProduct = getProductById(productId);

        productRepository.delete(existingProduct);
    }

}
