# Production PostgreSQL values come from Render environment variables
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Temporary until Flyway is implemented
spring.jpa.hibernate.ddl-auto=update

# Do not print every SQL query in production logs
spring.jpa.show-sql=false

# Disable detailed SQL formatting in production
spring.jpa.properties.hibernate.format_sql=false