# Local PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb

# Local PostgreSQL credentials
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:postgres}

# PostgreSQL JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Temporary setting while developing.
# Hibernate creates or updates tables based on entity classes.
spring.jpa.hibernate.ddl-auto=update

# Display generated SQL in the IntelliJ console
spring.jpa.show-sql=true

# Format SQL to make it easier to read
spring.jpa.properties.hibernate.format_sql=true