# Application name
spring.application.name=product-api

# Render provides PORT dynamically.
# Locally, the application uses port 8080.
server.port=${PORT:8080}

# H2 in-memory database configuration
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Automatically create or update database tables
spring.jpa.hibernate.ddl-auto=update

# Display generated SQL in the application console
spring.jpa.show-sql=true

# Format SQL for readability
spring.jpa.properties.hibernate.format_sql=true

# Enable the H2 browser console
spring.h2.console.enabled=true

# H2 console endpoint
spring.h2.console.path=/h2-console

# Actuator endpoints
management.endpoints.web.exposure.include=health,info